### ISSUE TITLE
Broken on Android SDK R18?

### ISSUE THREAD

**Issue by festerman** [michelou/android-examples#1]
Great stuff! -- but needed at least one hack to the ant stuff: it appears that in Android SDK R18 the path id `jar.libs.ref` has fallen out of the ant setup (I guess), so I had to resort to adding this to build-scala.xml:

```
<path id="jar.libs.ref">
  <fileset dir="${jar.libs.absolute.dir}" includes="*.jar" />
  <path refid="project.libraries.jars" />
</path>
```

(stolen from http://stackoverflow.com/questions/5312478/how-do-i-reference-external-jar-files-in-a-common-directory-not-libs-to-build).

(I also added a target `my-compile-scala` depending on `-compile-scala`, as I couldn't figure out how to run the target `-compile-scala`: ant keeps complaining about the hyphen ... it's probably just me being dense :-)

In addition, the project needs a update before the first build:

```
> cd android-sdk/HelloActivity
> android update project -p . --target <something>
```

(where `<something>` comes from `> android list targets`) to build local.properties and update project.properties.

As a reference, here are the versions I'm using:

1) Sun Java SDK 1.7.0_3
2) Scala SDK 2.9.1.r0-b20110831114755
3) Android SDK 18
4) Apache Ant 1.8.3
5) ProGuard 4.7

Cheers /festerman

**Comment by michelou** [comment]
Thanks for your feedback!

The easiest (and fastest) way to adapt `build-scala.xml` to the latest version (currently R19) of the Android SDK is to edit the file `android-sdk/configs/ant/build-scala.xml` as follows:

1) remove line 45 (referring to no longer existing `jar.libs.ref`
2) add the 2 path elements you mention in your message on line 49

and then execute `ant setenv` in directory `android-sdk` (it will update both `build-scala.xml` and `local.properties` in all subprojects)

NB. The above steps also apply to the other projects such as `cw-android`, `unlocking-android`, etc.

In the same manner you can change target `-compile-scala` to `compile-scala` in all `build-scala.xml` (actually I can't remember why I prepended the hyphen to that task!).

I will push the updates both to my GitHub repository and to my personal website asap.

Bye
--Stephane

PS. Also consider upgrading your Scala distribution to version 2.9.2 !

**Comment by festerman** [comment]
Thanks for the tip about `ant setenv`. I'll do the changes as suggested and try that.

I'll update the scala installation (was updated to 2.9.2 in the Arch package archive today ...). Android-sdk r18 seems a bit broken, and r19 just a quick fix to that, and r20 coming in just a few weeks (http://bit.ly/HQsmmS) so you might want to wait with the porting a bit.

I was also thinking about getting it to build from inside Eclipse ... The simplistic approach would be as calls on ant as external tool, I guess ...

Cheers /festerman
